server:
  port: 8888
  context-path: /CallMe
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: root
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true
#进行该配置后，每次启动程序，程序都会运行resources/db/schema.sql文件，对数据库的结构进行操作。
#spring.datasource.schema=classpath:db/schema.sql
#进行该配置后，每次启动程序，程序都会运行resources/db/data.sql文件，对数据库的数据操作。
#spring.datasource.data=classpath:db/data.sql
