server:
  port: 8888
  context-path: /CallMe
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CallMe?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
#debug: true
